"""baseline

Revision ID: 15e059b580f1
Revises: 
Create Date: 2025-12-09 10:04:11.150326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15e059b580f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False, comment='Nome completo do usuario.'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='E-mail utilizado para login na plataforma.'),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nivel', sa.Enum('ADMINISTRADOR', 'COMUM', name='usuario_nivel'), server_default=sa.text("'COMUM'::usuario_nivel"), nullable=False, comment='Nivel global do usuario na plataforma SaaS. ADMINISTRADOR = acesso total ao sistema. COMUM = usuario padrao.'),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key'),
    comment='Cadastro geral de usuarios da plataforma.'
    )
    op.create_index('idx_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_table('acesso',
    sa.Column('acesso_id', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.usuario_id'], name='acesso_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('acesso_id', name='acesso_pkey'),
    sa.UniqueConstraint('token', name='acesso_token_key')
    )
    op.create_table('empresas',
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('razao_social', sa.String(length=120), nullable=False, comment='Razao social da empresa.'),
    sa.Column('cnpj', sa.String(length=14), nullable=False, comment='CNPJ da empresa, sem formatacao.'),
    sa.Column('anfitria_usuario_id', sa.BigInteger(), nullable=False, comment='Usuario que criou a empresa (anfitriao/superadmin).'),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'America/Sao_Paulo'::character varying"), nullable=False, comment='Fuso horario da empresa no padrao IANA (ex: America/Sao_Paulo).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fantasia', sa.String(length=120), nullable=True, comment='Nome fantasia da empresa.'),
    sa.ForeignKeyConstraint(['anfitria_usuario_id'], ['usuarios.usuario_id'], name='empresas_anfitria_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('empresa_id', name='empresas_pkey'),
    sa.UniqueConstraint('cnpj', name='empresas_cnpj_key'),
    comment='Empresas cadastradas na plataforma (multi-tenant).'
    )
    op.create_index('idx_empresas_cnpj', 'empresas', ['cnpj'], unique=False)
    op.create_index('idx_empresas_timezone', 'empresas', ['timezone'], unique=False)
    op.create_table('certificados',
    sa.Column('certificado_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('criado_por', sa.BigInteger(), nullable=False),
    sa.Column('nome_arquivo', sa.Text(), nullable=False, comment='Nome original do arquivo de certificado.'),
    sa.Column('encrypted', sa.Text(), nullable=False, comment='Dados do certificado em formato criptografado.'),
    sa.Column('secret', sa.Text(), nullable=False, comment='Frase secreta ou chave auxiliar usada na criptografia.'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('proprietario', sa.String(), nullable=True, comment='Proprietario do certificado'),
    sa.Column('emitido_por', sa.String(), nullable=True, comment='Nome da entidade emissora do certificado'),
    sa.Column('validade_inicio', sa.DateTime(timezone=True), nullable=True, comment='Data de inicio da validade'),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True, comment='Data do fim da validade'),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.usuario_id'], name='certificados_usuario_fk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='certificados_empresa_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificado_id', name='certificados_pkey'),
    comment='Certificados digitais criptografados das empresas.'
    )
    op.create_index('idx_cert_criado_por', 'certificados', ['criado_por'], unique=False)
    op.create_index('idx_cert_emp', 'certificados', ['empresa_id'], unique=False)
    op.create_table('empresa_convites',
    sa.Column('convite_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('email_convidado', sa.String(length=150), nullable=False, comment='E-mail da pessoa convidada para entrar na empresa.'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pendente'::character varying"), nullable=False, comment='Status do convite: pendente, aceito, expirado ou cancelado.'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('convite_uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('convidado_usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('expiracao', sa.DateTime(), server_default=sa.text("(now() + '7 days'::interval)"), nullable=True),
    sa.ForeignKeyConstraint(['convidado_usuario_id'], ['usuarios.usuario_id'], name='convites_usuario_fk', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='convites_empresa_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('convite_id', name='empresa_convites_pkey'),
    sa.UniqueConstraint('convite_uuid', name='empresa_convites_uuid_unq'),
    comment='Convites enviados por e-mail para adicionar membros Ë empresa.'
    )
    op.create_table('empresa_membros',
    sa.Column('membro_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('papel', sa.Enum('ADMINISTRADOR', 'COMUM', name='usuario_nivel'), server_default=sa.text("'COMUM'::usuario_nivel"), nullable=False, comment='Papel do usuario na empresa (superadmin, admin, user, etc.).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='membros_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], name='membros_usuario_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membro_id', name='empresa_membros_pkey'),
    sa.UniqueConstraint('empresa_id', 'usuario_id', name='empresa_membros_unq'),
    comment='Relaciona usuarios e empresas, com o papel de cada um.'
    )
    op.create_index('idx_emp_membros_emp', 'empresa_membros', ['empresa_id'], unique=False)
    op.create_index('idx_emp_membros_user', 'empresa_membros', ['usuario_id'], unique=False)
    op.create_table('feriados',
    sa.Column('feriado_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('recorrente', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica se o feriado se repete todos os anos na mesma data.'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='feriados_empresa_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feriado_id', name='feriados_pkey'),
    comment='Feriados cadastrados por empresa, usados para bloquear acessos.'
    )
    op.create_index('idx_feriados_emp_data', 'feriados', ['empresa_id', 'data'], unique=False)
    op.create_table('planos_trabalho',
    sa.Column('plano_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do plano de trabalho (deve ser unico dentro da empresa).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='planos_empresa_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plano_id', name='planos_trabalho_pkey'),
    sa.UniqueConstraint('empresa_id', 'nome', name='planos_trabalho_unq'),
    comment='Planos de trabalho de uma empresa (modelos de regras e grupos).'
    )
    op.create_index('idx_planos_emp', 'planos_trabalho', ['empresa_id'], unique=False)
    op.create_table('grupos',
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('plano_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do grupo (unico dentro da empresa).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='grupos_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_trabalho.plano_id'], name='grupos_plano_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', name='grupos_pkey'),
    sa.UniqueConstraint('empresa_id', 'nome', name='grupos_unq'),
    comment='Grupos de usuarios pertencentes a planos de trabalho de uma empresa.'
    )
    op.create_index('idx_grupos_emp', 'grupos', ['empresa_id'], unique=False)
    op.create_index('idx_grupos_plano', 'grupos', ['plano_id'], unique=False)
    op.create_table('grupos_certificados',
    sa.Column('grupo_cert_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('certificado_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados.certificado_id'], name='grupos_certificados_cert_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='grupos_certificados_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='grupos_certificados_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_cert_id', name='grupos_certificados_pkey'),
    sa.UniqueConstraint('grupo_id', 'certificado_id', name='grupos_certificados_unq'),
    comment='Relacao de quais certificados cada grupo pode acessar.'
    )
    op.create_index('idx_g_cert_cert', 'grupos_certificados', ['certificado_id'], unique=False)
    op.create_index('idx_g_cert_emp', 'grupos_certificados', ['empresa_id'], unique=False)
    op.create_index('idx_g_cert_grupo', 'grupos_certificados', ['grupo_id'], unique=False)
    op.create_table('grupos_usuarios',
    sa.Column('grupo_usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='grupos_usuarios_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='grupos_usuarios_grupo_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], name='grupos_usuarios_usuario_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_usuario_id', name='grupos_usuarios_pkey'),
    sa.UniqueConstraint('grupo_id', 'usuario_id', name='grupos_usuarios_unq'),
    comment='Relacao entre usuarios e grupos, dentro de uma empresa.'
    )
    op.create_index('idx_g_usuarios_emp', 'grupos_usuarios', ['empresa_id'], unique=False)
    op.create_index('idx_g_usuarios_grupo', 'grupos_usuarios', ['grupo_id'], unique=False)
    op.create_index('idx_g_usuarios_user', 'grupos_usuarios', ['usuario_id'], unique=False)
    op.create_table('regras_acesso',
    sa.Column('regra_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False, comment='Tipo de regra: corridos, uteis ou especificos.'),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lista de janelas de horario em JSON (inicio/fim no formato HH:MI).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dias_especificos', sa.ARRAY(sa.Integer()), nullable=True, comment='Lista de dias (ex: 1=segunda ... 7=domingo) quando tipo_dia = especificos.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='regras_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='regras_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regra_id', name='regras_acesso_pkey'),
    comment='Regras de dias e horarios permitidos para grupos de uma empresa.'
    )
    op.create_index('idx_regras_acesso_hosts_emp', 'regras_acesso', ['empresa_id'], unique=False)
    op.create_index('idx_regras_acesso_hosts_grupo', 'regras_acesso', ['grupo_id'], unique=False)
    op.create_index('idx_regras_emp', 'regras_acesso', ['empresa_id'], unique=False)
    op.create_index('idx_regras_grupo', 'regras_acesso', ['grupo_id'], unique=False)
    op.create_table('regras_acesso_hosts',
    sa.Column('regra_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dias_especificos', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], name='regras_empresa_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='regras_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regra_id', name='regras_acesso_hosts_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regras_acesso_hosts')
    op.drop_index('idx_regras_grupo', table_name='regras_acesso')
    op.drop_index('idx_regras_emp', table_name='regras_acesso')
    op.drop_index('idx_regras_acesso_hosts_grupo', table_name='regras_acesso')
    op.drop_index('idx_regras_acesso_hosts_emp', table_name='regras_acesso')
    op.drop_table('regras_acesso')
    op.drop_index('idx_g_usuarios_user', table_name='grupos_usuarios')
    op.drop_index('idx_g_usuarios_grupo', table_name='grupos_usuarios')
    op.drop_index('idx_g_usuarios_emp', table_name='grupos_usuarios')
    op.drop_table('grupos_usuarios')
    op.drop_index('idx_g_cert_grupo', table_name='grupos_certificados')
    op.drop_index('idx_g_cert_emp', table_name='grupos_certificados')
    op.drop_index('idx_g_cert_cert', table_name='grupos_certificados')
    op.drop_table('grupos_certificados')
    op.drop_index('idx_grupos_plano', table_name='grupos')
    op.drop_index('idx_grupos_emp', table_name='grupos')
    op.drop_table('grupos')
    op.drop_index('idx_planos_emp', table_name='planos_trabalho')
    op.drop_table('planos_trabalho')
    op.drop_index('idx_feriados_emp_data', table_name='feriados')
    op.drop_table('feriados')
    op.drop_index('idx_emp_membros_user', table_name='empresa_membros')
    op.drop_index('idx_emp_membros_emp', table_name='empresa_membros')
    op.drop_table('empresa_membros')
    op.drop_table('empresa_convites')
    op.drop_index('idx_cert_emp', table_name='certificados')
    op.drop_index('idx_cert_criado_por', table_name='certificados')
    op.drop_table('certificados')
    op.drop_index('idx_empresas_timezone', table_name='empresas')
    op.drop_index('idx_empresas_cnpj', table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('acesso')
    op.drop_index('idx_usuarios_email', table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
