"""initial

Revision ID: 26e33622df6e
Revises: 
Create Date: 2026-02-17 16:25:35.375820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26e33622df6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados',
    sa.Column('certificado_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('criado_por', sa.UUID(), nullable=False, comment='ID do usuario que criou (validado pelo Auth service)'),
    sa.Column('nome_arquivo', sa.Text(), nullable=False, comment='Nome original do arquivo de certificado.'),
    sa.Column('encrypted', sa.Text(), nullable=False, comment='Dados do certificado em formato criptografado.'),
    sa.Column('secret', sa.Text(), nullable=False, comment='Frase secreta ou chave auxiliar usada na criptografia.'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('proprietario', sa.String(), nullable=True, comment='Proprietario do certificado'),
    sa.Column('emitido_por', sa.String(), nullable=True, comment='Nome da entidade emissora do certificado'),
    sa.Column('validade_inicio', sa.DateTime(timezone=True), nullable=True, comment='Data de inicio da validade'),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True, comment='Data do fim da validade'),
    sa.Column('cofre_cert_id', sa.UUID(), nullable=True, comment='ID do certificado no servico Cofre'),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica se o certificado esta ativo para uso'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Data/hora da exclusao (soft delete)'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='ID do usuario que excluiu o certificado'),
    sa.PrimaryKeyConstraint('certificado_id', name='certificados_pkey'),
    comment='Certificados digitais criptografados das empresas.'
    )
    op.create_index('idx_cert_criado_por', 'certificados', ['criado_por'], unique=False)
    op.create_index('idx_cert_emp', 'certificados', ['empresa_id'], unique=False)
    op.create_table('feriados',
    sa.Column('feriado_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('recorrente', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica se o feriado se repete todos os anos na mesma data.'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('feriado_id', name='feriados_pkey'),
    comment='Feriados cadastrados por empresa, usados para bloquear acessos.'
    )
    op.create_index('idx_feriados_emp', 'feriados', ['empresa_id'], unique=False)
    op.create_table('global_urls',
    sa.Column('global_urls_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador unico'),
    sa.Column('url', sa.Text(), nullable=True, comment='URL cadastrada'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Data de criacao'),
    sa.Column('inativo', sa.Boolean(), server_default=sa.text('false'), nullable=True, comment='Indica se a URL esta inativa'),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.PrimaryKeyConstraint('global_urls_id', name='global_urls_pkey'),
    comment='URLs globais cadastradas por empresa.'
    )
    op.create_index('idx_global_urls_emp', 'global_urls', ['empresa_id'], unique=False)
    op.create_table('planos_trabalho',
    sa.Column('plano_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do plano de trabalho (deve ser unico dentro da empresa).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('plano_id', name='planos_trabalho_pkey'),
    sa.UniqueConstraint('empresa_id', 'nome', name='planos_trabalho_empresa_nome_unq'),
    comment='Planos de trabalho de uma empresa (modelos de regras e grupos).'
    )
    op.create_index('idx_planos_trabalho_emp', 'planos_trabalho', ['empresa_id'], unique=False)
    op.create_table('usuarios_ip_whitelist',
    sa.Column('whitelist_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuario (validado pelo Auth service)'),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Endereco IP permitido (IPv4 ou IPv6)'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descricao opcional para referencia do admin'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=False, comment='ID do admin que criou a entrada'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Data/hora da exclusao (soft delete)'),
    sa.Column('deleted_by', sa.UUID(), nullable=True, comment='ID do usuario que excluiu'),
    sa.PrimaryKeyConstraint('whitelist_id', name='usuarios_ip_whitelist_pkey'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', 'ip_address', name='usuarios_ip_whitelist_unq'),
    comment='Lista de IPs permitidos por usuario e empresa.'
    )
    op.create_index('idx_usuarios_ip_whitelist_empresa', 'usuarios_ip_whitelist', ['empresa_id'], unique=False)
    op.create_index('idx_usuarios_ip_whitelist_ip', 'usuarios_ip_whitelist', ['ip_address'], unique=False)
    op.create_index('idx_usuarios_ip_whitelist_usuario', 'usuarios_ip_whitelist', ['usuario_id'], unique=False)
    op.create_table('grupos',
    sa.Column('grupo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('plano_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do grupo (unico dentro da empresa).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_trabalho.plano_id'], name='grupos_plano_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', name='grupos_pkey'),
    sa.UniqueConstraint('empresa_id', 'nome', name='grupos_empresa_nome_unq'),
    comment='Grupos de usuarios pertencentes a planos de trabalho de uma empresa.'
    )
    op.create_index('idx_grupos_emp', 'grupos', ['empresa_id'], unique=False)
    op.create_index('idx_grupos_plano', 'grupos', ['plano_id'], unique=False)
    op.create_table('grupos_certificados',
    sa.Column('grupo_cert_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('certificado_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados.certificado_id'], name='grupos_certificados_cert_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='grupos_certificados_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_cert_id', name='grupos_certificados_pkey'),
    sa.UniqueConstraint('grupo_id', 'certificado_id', name='grupos_certificados_unq'),
    comment='Relacao de quais certificados cada grupo pode acessar.'
    )
    op.create_index('idx_g_cert_cert', 'grupos_certificados', ['certificado_id'], unique=False)
    op.create_index('idx_g_cert_emp', 'grupos_certificados', ['empresa_id'], unique=False)
    op.create_index('idx_g_cert_grupo', 'grupos_certificados', ['grupo_id'], unique=False)
    op.create_table('grupos_usuarios',
    sa.Column('grupo_usuario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuario (validado pelo Auth service)'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='grupos_usuarios_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_usuario_id', name='grupos_usuarios_pkey'),
    sa.UniqueConstraint('grupo_id', 'usuario_id', name='grupos_usuarios_unq'),
    comment='Relacao entre usuarios e grupos, dentro de uma empresa.'
    )
    op.create_index('idx_g_usuarios_emp', 'grupos_usuarios', ['empresa_id'], unique=False)
    op.create_index('idx_g_usuarios_grupo', 'grupos_usuarios', ['grupo_id'], unique=False)
    op.create_index('idx_g_usuarios_user', 'grupos_usuarios', ['usuario_id'], unique=False)
    op.create_table('regras_acesso',
    sa.Column('regra_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False, comment='Tipo de regra: corridos, uteis ou especificos.'),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lista de janelas de horario em JSON (inicio/fim no formato HH:MI).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dias_especificos', sa.ARRAY(sa.Integer()), nullable=True, comment='Lista de dias (ex: 1=segunda ... 7=domingo) quando tipo_dia = especificos.'),
    sa.Column('bloquear_em_feriado', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Bloqueia acesso em feriados da empresa.'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='regras_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regra_id', name='regras_acesso_pkey'),
    comment='Regras de dias e horarios permitidos para grupos de uma empresa.'
    )
    op.create_index('idx_regras_emp', 'regras_acesso', ['empresa_id'], unique=False)
    op.create_index('idx_regras_grupo', 'regras_acesso', ['grupo_id'], unique=False)
    op.create_table('regras_acesso_ips',
    sa.Column('regra_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('ip_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lista de enderecos IP (IPv4, IPv6 ou blocos CIDR)'),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False, comment='Tipo de regra: corridos, uteis ou especificos.'),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lista de janelas de horario em JSON (inicio/fim no formato HH:MI).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dias_especificos', sa.ARRAY(sa.Integer()), nullable=True, comment='Lista de dias (ex: 1=segunda ... 7=domingo) quando tipo_dia = especificos.'),
    sa.Column('bloquear_em_feriado', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Bloqueia acesso em feriados da empresa.'),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica se a regra esta ativa.'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='regras_acesso_ips_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regra_id', name='regras_acesso_ips_pkey'),
    comment='Regras de dias e horarios permitidos para enderecos IP especificos de um grupo.'
    )
    op.create_index('idx_regras_acesso_ips_emp', 'regras_acesso_ips', ['empresa_id'], unique=False)
    op.create_index('idx_regras_acesso_ips_grupo', 'regras_acesso_ips', ['grupo_id'], unique=False)
    op.create_table('regras_acesso_urls',
    sa.Column('regra_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('global_urls_id', sa.UUID(), nullable=False),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False, comment='Tipo de regra: corridos, uteis ou especificos.'),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Lista de janelas de horario em JSON (inicio/fim no formato HH:MI).'),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('dias_especificos', sa.ARRAY(sa.Integer()), nullable=True, comment='Lista de dias (ex: 1=segunda ... 7=domingo) quando tipo_dia = especificos.'),
    sa.Column('bloquear_em_feriado', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Bloqueia acesso em feriados da empresa.'),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica se a regra esta ativa.'),
    sa.ForeignKeyConstraint(['global_urls_id'], ['global_urls.global_urls_id'], name='regras_acesso_urls_url_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.grupo_id'], name='regras_acesso_urls_grupo_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('regra_id', name='regras_acesso_urls_pkey'),
    sa.UniqueConstraint('grupo_id', 'global_urls_id', name='regras_acesso_urls_grupo_url_unq'),
    comment='Regras de dias e horarios permitidos para URLs especificas de um grupo.'
    )
    op.create_index('idx_regras_acesso_urls_emp', 'regras_acesso_urls', ['empresa_id'], unique=False)
    op.create_index('idx_regras_acesso_urls_grupo', 'regras_acesso_urls', ['grupo_id'], unique=False)
    op.create_index('idx_regras_acesso_urls_url', 'regras_acesso_urls', ['global_urls_id'], unique=False)
    op.create_table('grupos_certificados_urls',
    sa.Column('grupo_cert_url_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='ID da empresa (validado pelo Auth service)'),
    sa.Column('grupo_cert_id', sa.UUID(), nullable=False),
    sa.Column('global_urls_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['global_urls_id'], ['global_urls.global_urls_id'], name='grupos_cert_urls_url_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_cert_id'], ['grupos_certificados.grupo_cert_id'], name='grupos_cert_urls_grupo_cert_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_cert_url_id', name='grupos_certificados_urls_pkey'),
    sa.UniqueConstraint('grupo_cert_id', 'global_urls_id', name='grupos_certificados_urls_unq'),
    comment='URLs permitidas para cada relacao grupo-certificado.'
    )
    op.create_index('idx_g_cert_urls_emp', 'grupos_certificados_urls', ['empresa_id'], unique=False)
    op.create_index('idx_g_cert_urls_grupo_cert', 'grupos_certificados_urls', ['grupo_cert_id'], unique=False)
    op.create_index('idx_g_cert_urls_url', 'grupos_certificados_urls', ['global_urls_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_g_cert_urls_url', table_name='grupos_certificados_urls')
    op.drop_index('idx_g_cert_urls_grupo_cert', table_name='grupos_certificados_urls')
    op.drop_index('idx_g_cert_urls_emp', table_name='grupos_certificados_urls')
    op.drop_table('grupos_certificados_urls')
    op.drop_index('idx_regras_acesso_urls_url', table_name='regras_acesso_urls')
    op.drop_index('idx_regras_acesso_urls_grupo', table_name='regras_acesso_urls')
    op.drop_index('idx_regras_acesso_urls_emp', table_name='regras_acesso_urls')
    op.drop_table('regras_acesso_urls')
    op.drop_index('idx_regras_acesso_ips_grupo', table_name='regras_acesso_ips')
    op.drop_index('idx_regras_acesso_ips_emp', table_name='regras_acesso_ips')
    op.drop_table('regras_acesso_ips')
    op.drop_index('idx_regras_grupo', table_name='regras_acesso')
    op.drop_index('idx_regras_emp', table_name='regras_acesso')
    op.drop_table('regras_acesso')
    op.drop_index('idx_g_usuarios_user', table_name='grupos_usuarios')
    op.drop_index('idx_g_usuarios_grupo', table_name='grupos_usuarios')
    op.drop_index('idx_g_usuarios_emp', table_name='grupos_usuarios')
    op.drop_table('grupos_usuarios')
    op.drop_index('idx_g_cert_grupo', table_name='grupos_certificados')
    op.drop_index('idx_g_cert_emp', table_name='grupos_certificados')
    op.drop_index('idx_g_cert_cert', table_name='grupos_certificados')
    op.drop_table('grupos_certificados')
    op.drop_index('idx_grupos_plano', table_name='grupos')
    op.drop_index('idx_grupos_emp', table_name='grupos')
    op.drop_table('grupos')
    op.drop_index('idx_usuarios_ip_whitelist_usuario', table_name='usuarios_ip_whitelist')
    op.drop_index('idx_usuarios_ip_whitelist_ip', table_name='usuarios_ip_whitelist')
    op.drop_index('idx_usuarios_ip_whitelist_empresa', table_name='usuarios_ip_whitelist')
    op.drop_table('usuarios_ip_whitelist')
    op.drop_index('idx_planos_trabalho_emp', table_name='planos_trabalho')
    op.drop_table('planos_trabalho')
    op.drop_index('idx_global_urls_emp', table_name='global_urls')
    op.drop_table('global_urls')
    op.drop_index('idx_feriados_emp', table_name='feriados')
    op.drop_table('feriados')
    op.drop_index('idx_cert_emp', table_name='certificados')
    op.drop_index('idx_cert_criado_por', table_name='certificados')
    op.drop_table('certificados')
    # ### end Alembic commands ###
